### ISSUE TITLE
support RSS

### ISSUE THREAD

**Issue by librabyte** [librabyte/hugo-theme-cosmos#31]
Hugo ships with its own [RSS 2.0 template](https://gohugo.io/templates/rss/#the-embedded-rssxml)

ref: https://gohugo.io/templates/rss/

**Comment by librabyte** [comment]
builtin rss template: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml

**Comment by librabyte** [comment]
add rss to your sites via updating the `config.toml`

```toml
  [[menu.main]]
    title = "rss"
    name = "rss"
    url = "/index.xml"
    weight = -20
```
